# Generated by Django 5.0.6 on 2024-07-04 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kanban.kanbantask'),
        ),
    ]
