# Generated by Django 5.0.6 on 2024-07-05 17:18

# kanban/migrations/0005_auto_20240705_1718.py

from django.db import migrations

def delete_in_progress_and_done(apps, schema_editor):
    Column = apps.get_model('kanban', 'Column')
    Board = apps.get_model('kanban', 'Board')
    User = apps.get_model('auth', 'User')

    for user in User.objects.all():
        try:
            board = Board.objects.get(owner=user, name='Default Board')
            Column.objects.filter(board=board, name__in=['In Progress', 'Done']).delete()
        except Board.DoesNotExist:
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_alter_kanbantask_priority'),
    ]

    operations = [
        migrations.RunPython(delete_in_progress_and_done),
    ]
