# Generated by Django 5.0.6 on 2024-07-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_auto_20240705_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kanbantask',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='kanbantask',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
