# Generated by Django 5.0.6 on 2024-07-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
