# Generated by Django 5.0.6 on 2024-07-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0011_profile_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='use_default_background',
            field=models.BooleanField(default=False),
        ),
    ]
